name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory : ./Experling-API/
    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: localhost:8080
          docker_name: owasp/zap2docker-stable
          allow_issue_writing: true
